# Generated by Django 4.1.6 on 2023-02-18 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_purchase_price_alter_movie_rental_price"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
