# Generated by Django 4.1.6 on 2023-02-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_remove_movie_genre_movie_genres"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="poster",
        ),
        migrations.AddField(
            model_name="movie",
            name="display_times",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="purchase_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="movie",
            name="rental_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.TimeField(),
        ),
    ]
