# Generated by Django 4.1.6 on 2023-02-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_remove_movie_poster_movie_display_times_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="display_times",
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.DurationField(),
        ),
        migrations.CreateModel(
            name="MovieDisplayTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("display_time", models.DateTimeField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
