# Generated by Django 4.1.6 on 2023-03-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_purchase_price_alter_movie_rental_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialMovieDump",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("has_been_dumped", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
